# Generated by Django 2.0.9 on 2018-10-29 09:47

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0040_page_draft_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='PymbakeFinishingPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('intro', models.CharField(blank=True, help_text='Finishing description', max_length=250, null=True)),
                ('pattern', models.BooleanField(default=False, help_text='Is it a 1x1 meter pattern?')),
                ('color', models.CharField(blank=True, help_text='Accepts hex (#ffffff) or HTML color', max_length=250, null=True)),
                ('tiling_height', models.CharField(default='0', help_text='Tiling height from floor in cm', max_length=250)),
                ('tiling_pattern', models.BooleanField(default=False, help_text='Is it a 1x1 meter pattern?')),
                ('tiling_color', models.CharField(default='white', help_text='Accepts hex (#ffffff) or HTML color', max_length=250)),
                ('skirting_height', models.CharField(default='0', help_text='Skirting height from floor in cm', max_length=250)),
                ('skirting_pattern', models.BooleanField(default=False, help_text='Is it a 1x1 meter pattern?')),
                ('skirting_color', models.CharField(default='white', help_text='Accepts hex (#ffffff) or HTML color', max_length=250)),
                ('image', models.ForeignKey(blank=True, help_text='Sets the finishing general appearance', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image')),
                ('skirting_image', models.ForeignKey(blank=True, help_text='Sets the skirting general appearance', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image')),
                ('tiling_image', models.ForeignKey(blank=True, help_text='Sets the tiling general appearance', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='PymbakeIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('introduction', models.TextField(blank=True, help_text='Text to describe the page')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='PymbakePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('intro', models.CharField(blank=True, help_text='Project description', max_length=250, null=True)),
                ('shadows', models.BooleanField(default=False, help_text='Want to cast shadows?')),
                ('fly_camera', models.BooleanField(default=False, help_text='Vertical movement of camera?')),
                ('double_face', models.BooleanField(default=False, help_text='Planes are visible on both sides?')),
                ('dxf_file', models.ForeignKey(help_text='CAD file of your project', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtaildocs.Document')),
                ('equirectangular_image', models.ForeignKey(blank=True, help_text='Landscape surrounding your project', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='PymbakePageMaterialImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('layer', models.CharField(default='0', help_text='Layer name in CAD file', max_length=250)),
                ('color', models.CharField(default='white', help_text='Accepts hex (#ffffff) or HTML color', max_length=250)),
                ('pattern', models.BooleanField(default=False, help_text='Is it a 1x1 meter pattern?')),
                ('invisible', models.BooleanField(default=False, help_text='Hide layer?')),
                ('image', models.ForeignKey(blank=True, help_text='Sets general appearance of material', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_images', to='pymbake.PymbakePage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PymbakePartitionPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('intro', models.CharField(blank=True, help_text='Partition description', max_length=250, null=True)),
                ('pattern', models.BooleanField(default=False, help_text='Is it a 1x1 meter pattern?')),
                ('color', models.CharField(blank=True, help_text='Accepts hex (#ffffff) or HTML color', max_length=250, null=True)),
                ('image', models.ForeignKey(blank=True, help_text='Sets the partition general appearance', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='PymbakePartitionPageLayers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('material', models.CharField(default='brick', help_text='Material description', max_length=250)),
                ('thickness', models.CharField(default='0', help_text='In centimeters', max_length=250)),
                ('weight', models.CharField(default='0', help_text='In kilos per cubic meter', max_length=250)),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='part_layers', to='pymbake.PymbakePartitionPage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
