# Generated by Django 2.0.9 on 2018-10-29 22:33

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        #('base', '0004_auto_20180522_1856'),
        ('pymbake', '0002_pymbakepage_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='PYMbakePeopleRelationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='pymbakepage',
            name='date_published',
            field=models.DateField(blank=True, null=True, verbose_name='Date article published'),
        ),
        migrations.AddField(
            model_name='pymbakepeoplerelationship',
            name='page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='pymbake_person_relationship', to='pymbake.PymbakePage'),
        ),
        migrations.AddField(
            model_name='pymbakepeoplerelationship',
            name='people',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='person_pymbake_relationship', to='base.People'),
        ),
    ]
